variables:
  CONTAINER_DEV_IMAGE: $CI_REGISTRY_IMAGE:dev
  CONTAINER_TAG_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:prod

stages:
  - build
  # - deploy

build:
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.git.shundaojia.com
  script:
    - docker build -t $CONTAINER_DEV_IMAGE .
    - docker push $CONTAINER_DEV_IMAGE
  stage: build
  only:
    - develop
  tags:
    - docker-builder

release-image:
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.git.shundaojia.com
  script:
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE
  stage: build
  only:
    - master
  tags:
    - docker-builder
